<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="_style.css" />
    <title>4 CHAR ERROR CODES</title>
</head>
<body>

    <div class="TITLE_BOX">
        <h1>FOUR CHARACTER ERROR CODES</h1>
    </div>

    <div class="_gray">

        <p>4 character error codes are those that follow the aTSP codes and are located in square brackets. These codes specify the general class of the exception.</p>

    </div>

    <a href="index.html">
        <button class="linker_button"><span>Back to Main</span></button>
    </a>

    <h1 class="NON_TITLE_H1"> Errors 0x1000 to 0x1FFF (FileIO-Related Errors)</h1>

    <div
    class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
    id="13EC">

        <h2>0x13EC</h2>

        <div class="_ind">
        <h3>CASE 1: EOFError</h3>
        <p><strong>End of File</strong> (EOF) errors occur when an interpreter reaches the end of a file's content unexpectedly/prematurely. Can be raised by:</p>
        <ul>
            <li>The PYTHON interpreter (an internal error)</li>
            <li>The QUIZZING APP FILE PARSER</li>
        </ul>

    </div>
    </div>

    <div
    class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
    id="13F6">

        <h2>0x13F6</h2>
    <div class="_ind">
        <h3>CASE 1: NotADirectoryError</h3>
        <p><strong>Not a Directory</strong> errors occur when a file IO function attempts to run a directory-specific command on an object that isn't a directory. Can occur if:</p>
        <ul>
            <li>The object is not a directory (is a file)</li>
            <li>The object does not exist</li>
        </ul>

    </div>
    </div>

    <div
    class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
    id="1400">

        <h2>0x1400</h2>
    <div class="_ind">
        <h3>CASE 1: IsADirectoryError</h3>
        <p><strong>Is a Directory</strong> errors occur when a file IO function attempts to run a non-directory command on an object that is a directory. Can occur if:</p>
        <ul>
            <li>The object is a directory (if trying to run a FileIO task (R/W) on an object that is a directory)</li>
            <li>The object does exist (if trying to create a directory that already exists, for example)</li>
        </ul>

    </div>
    </div>

    <div
    class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
    id="141E">

        <h2>0x141E</h2>

        <div class="_ind">
        <h3>CASE 1: FileNotFoundError</h3>
        <p><strong>File Not Found</strong> errors occur when a file IO function attempts to run a file-specific command on an object that does not exist. Can occur if:</p>
        <ul>
            <li>The object is not a file</li>
            <li>The object does not exist</li>
        </ul>

        </div>
    </div>

    <div
    class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
    id="15E0">

        <h2>0x15E0</h2>

        <div class="_ind">
        <h3>CASE 1: FileExistsError</h3>
        <p><strong>File Exists</strong> errors occur when a file IO function attempts to run a command on a file object that does exist. Can occur if:</p>
        <ul>
            <li>The object does exist (if a file IO function is trying to create a file that already exists.)</li>
        </ul>

        </div>
    </div>

    <h1 class="NON_TITLE_H1">Errors 0x2000 to 0x2FFF (General Errors)</h1>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="23EA"
    >

        <h2>0x23EA</h2>

        <div class="_ind">
            <h3>CASE 1: TypeError</h3>
            <p><strong>Type</strong> errors occur when the wrong type of data is passed to a function.</p>
            <ul>
                <li>An internal error</li>
            </ul>

        </div>
    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="23F3"
    >

        <h2>0x23F3</h2>

        <div class="_ind">
            <h3>CASE 1: AttributeError</h3>
            <p><strong>Attribute</strong> errors occur when unexpected data is passed to a function.</p>
            <ul>
                <li>An internal error</li>
            </ul>

        </div>
    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="23F4"
    >

        <h2>0x23F4</h2>

    <div class="_ind">
        <h3>CASE 1: NameError</h3>
        <p><strong>Name</strong> errors occur when an undeclared variable is accessed.</p>
        <ul>
            <li>An internal error</li>
        </ul>

    </div>
    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="244D"
    >

        <h2>0x244D</h2>

    <div class="_ind">
        <h3>CASE 1: ValueError</h3>
        <p>Same as <a href="#23F3">23F3 Attribute Error</a>.</p>

    </div>
    </div>

    <h1 class="NON_TITLE_H1">Errors 0x3000 to 0x3FFF (General Python Errors - P0 TYPE ERRORS)</h1>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="33F2"
    >

        <h2>0x33F2</h2>
    <div class="_ind">
        <h3>CASE 1: Exception</h3>
        <p>A generic exception.</p>

    </div>
    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="33FC"
    >
        <h2>0x33FC</h2>

    <div class="_ind">
        <h3>CASE 1: Base Exception</h3>
        <p>A <strong>BaseException</strong> type error is raised anytime a (custom) exception defined and raised by the quizzing application suite (such as qa_def.NotYetImplemented).</p>

        <h3>CASE 2: BlockingIOError</h3>
        <p>An internal, python error (P0).</p>

        <h3>CASE 3: BrokenPipeError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 4: BufferError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 5: ChildProcessError</h3>
        <ul>
            <li>An internal, python error (P0)</li>
            <li>Can occur if a subprocess called by the quizzing app suite (such as the theme download prompt) encounters an error and does not catch it.</li>
        </ul>

        <h3>CASE 6: ConnectionAbortedError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 7: ConnectionError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 8: ConnectionRefusedError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 9: ConnectionResetError</h3>
        <p>An internal, python error (P0)</p>

        <h3 id="import_error">CASE 10: ImportError</h3>
        <p>An internal, python error (P0); can occur if (when in development mode), a dependency of the application is not met. Check PYTHON DEPENDENCIES fore more information.</p>

        <h3>CASE 11: IndentationError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 12: IndexError</h3>
        <p>An internal, python error (P0); occurs when a list/tuple/set is accessed at an index that does not exist.</p>

        <h3>CASE 13: KeyError</h3>
        <p>An internal, python error (P0); occurs when a dict is accessed with a key that it does not contain.</p>

        <h3>CASE 14: InterruptedError</h3>
        <p>An internal, python error (P0). <strong>KEYBOARD INTERRUPTS ARE NOT CAUGHT BY THE GLOBAL ERROR MANAGER BY DESIGN.</strong></p>

        <h3>CASE 15: LookupError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 16: ModuleNotFoundError</h3>
        <p>An internal, python error (P0); akin to <a href="#import_error">CASE 10: ImportError</a>.</p>

        <h3>CASE 17: NotImplementedError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 18: OverflowError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 19: ProcessLookupError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 20: ReferenceError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 21: TabError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 22: TimeoutError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 23: UnboundLocalError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 24: UnicodeError</h3>
        <p>An internal, python error (P0); can occur when trying to access a file that was created with a different encoding (different locale).</p>

        <h3>CASE 25: UnicodeWarning</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 26: UnicodeDecodeError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 27: UnicodeEncodeError</h3>
        <p>An internal, python error (P0)</p>

        <h3>CASE 28: UnicodeTranslateError</h3>
        <p>An internal, python error (P0)</p>

    </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="33F3"
    >

        <h2>0x33F3</h2>

        <div class="_ind">

            <h3>CASE 1: AssertionError</h3>
            <p>Occurs when unexpected data is encountered by a function, or when essential functions fail.</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="33F4"
    >

        <h2>0x33F4</h2>

        <div class="_ind">

            <h3>CASE 1: PermissionError</h3>
            <p>Occurs when an operating-system level command is run without sufficient permissions. Usually caused by FileIO functions.</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="33F6"
    >


        <h2>0x33F6</h2>

        <div class="_ind">
            <h3>CASE 1: RecursionError</h3>
            <p>Occurs when a recursive function cycles too many times.</p>
        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="33F7"
    >

        <h2>0x33F7</h2>

        <div class="_ind">

        <h3>CASE 1: SystemError</h3>
        <p>Results from a failure stemming from the operating system API (SYS and OS modules in python)</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="33FF"
    >

        <h2>0x33FF</h2>

        <div class="_ind">

            <h3>CASE 1: Memory Error</h3>
            <p>An internal, python  error (P0).</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="3400"
    >

        <h2>0x3400</h2>

        <div class="_ind">

            <h3>CASE 1: RuntimeError</h3>
            <p>An internal, python  error (P0).</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="3401"
    >

        <h2>0x3401</h2>

        <div class="_ind">

            <h3>CASE 1: Runtime Warning</h3>
            <p>An internal, python  error (P0).</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="3402"
    >

        <h2>0x3402</h2>

        <div class="_ind">

            <h3>CASE 1: Syntax Warning</h3>
            <p>An internal, python  error (P0).</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="3403"
    >

        <h2>0x3403</h2>

        <div class="_ind">

            <h3>CASE 1: Syntax Error</h3>
            <p>An internal, python  error (P0).</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="3410"
    >

        <h2>0x3410</h2>

        <div class="_ind">

            <h3>CASE 1: IOError</h3>
            <p>An internal, python error (P0) -- these errors are not raised by the quizzing application FileIO handler.</p>

            <h3>CASE 2: EnvironmentError</h3>
            <p>An internal, python error (P0).</p>

            <h3>CASE 3: OSError</h3>
            <p>An internal, python error (P0).</p>

            <h3>CASE 4: WindowsError</h3>
            <p>An internal, python error (P0) -- same as OSError on Windows machines.</p>

        </div>

    </div>

    <h1 class="NON_TITLE_H1">Errors 0x4000 to 0x4FFF (Arithmetic Errors)</h1>

     <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="43F3"
    >

        <h2>0x43F3</h2>

        <div class="_ind">

            <h3>CASE 1: Floating Point Error</h3>
            <p>Occurs when a floating-point number encounters an error (P1 type).</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="44BD"
    >

        <h2>0x44BD</h2>

        <div class="_ind">

            <h3>CASE 1: ZeroDivisionError</h3>
            <p>Occurs when a division by zero event occurs; usually the result of invalid array computations (P1 type).</p>

        </div>

    </div>

    <div
        class="FOUR_CHAR_ERROR_CODE_DESCRIPTION"
        id="45E6"
    >

        <h2>0x45E6</h2>

        <div class="_ind">

            <h3>CASE 1: Arithmetic Error</h3>
            <p>General Arithmetic Errors (P1 type).</p>

        </div>

    </div>

</body>
</html>